### ISSUE TITLE
Plugin is not Python 3-compatible

### ISSUE THREAD

**Issue by Genda1ph** [cmacmackin/figure-ref#1]
Hello.
I've installed your plugin on Pelican 3.6.3 (Python 3.5).
When I run Pelican I see a warning:
WARNING: Caught exception "NameError: name 'unicode' is not defined". Reloading.

This is a critical error since no rendering is being done as a result.
Error is caused by changes introduced in Python 3, str and unicode types where renamed:
str -> bytes
unicode -> str

http://stackoverflow.com/questions/19877306/nameerror-global-name-unicode-is-not-defined-in-python-3

Patch for Python 3 (breaks compatibility with Python 2)
[py3.patch.txt](https://github.com/cmacmackin/figure-ref/files/67670/py3.patch.txt)

**Comment by cmacmackin** [comment]
I have fixed this and pushed the changes to the repository. I have also made a pull request with the Pelican Plugins repository, so hopefully the changes will show up there in a day or two.
